// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分20秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function Common_UIPopupBG_5S.Common_UIPopupBG_5S_C.Construct
struct UCommon_UIPopupBG_5S_C_Construct_Params
{
};

// Function Common_UIPopupBG_5S.Common_UIPopupBG_5S_C.ExecuteUbergraph_Common_UIPopupBG_5S
struct UCommon_UIPopupBG_5S_C_ExecuteUbergraph_Common_UIPopupBG_5S_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

