// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分16秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function SettingConfig.SettingConfig_C.ConditionSetFireGyroData
struct USettingConfig_C_ConditionSetFireGyroData_Params
{
};

// Function SettingConfig.SettingConfig_C.Init
struct USettingConfig_C_Init_Params
{
};

}

