// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分17秒
namespace SDK
{
//
//Script Structs
//

// UserDefinedStruct BP_STRUCT_VNGMenuSwitchTable_type.BP_STRUCT_VNGMenuSwitchTable_type
// 0x0008
struct FBP_STRUCT_VNGMenuSwitchTable_type
{
	int                                                ID_0_7E289F40058F21997AC26B640BB07F84;                    // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                Open_1_0148C0806D55EA324F39ACAD00803D0E;                  // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

