// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分21秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function Common_BackgroundBlur.Common_BackgroundBlur_C.Construct
struct UCommon_BackgroundBlur_C_Construct_Params
{
};

// Function Common_BackgroundBlur.Common_BackgroundBlur_C.ExecuteUbergraph_Common_BackgroundBlur
struct UCommon_BackgroundBlur_C_ExecuteUbergraph_Common_BackgroundBlur_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

