// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分08秒
namespace SDK
{
//
//Classes
//

// Class PixUIFileDialog.PxFileDiaLogObj
// 0x0000 (0x0028 - 0x0028)
class UPxFileDiaLogObj : public UObject
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("Class PixUIFileDialog.PxFileDiaLogObj");
		return pStaticClass;
	}

};


}

