// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分20秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function NewLogin_UIBP.NewLogin_UIBP_C.SetRenderTransformWheniPhone
struct UNewLogin_UIBP_C_SetRenderTransformWheniPhone_Params
{
};

// Function NewLogin_UIBP.NewLogin_UIBP_C.Construct
struct UNewLogin_UIBP_C_Construct_Params
{
};

// Function NewLogin_UIBP.NewLogin_UIBP_C.ExecuteUbergraph_NewLogin_UIBP
struct UNewLogin_UIBP_C_ExecuteUbergraph_NewLogin_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

