// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分13秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function BP_CustomLayoutProxy.BP_CustomLayoutProxy_C.AddLayoutDetailCache
struct UBP_CustomLayoutProxy_C_AddLayoutDetailCache_Params
{
	struct FBP_STRUCT_UIElemLayoutDetail               BPStruct;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                               Invalid;                                                  // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

