// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分18秒
namespace SDK
{
//
//Enums
//

// UserDefinedEnum EnumAvatarForceGender.EnumAvatarForceGender
enum class EnumAvatarForceGender : uint8_t
{
	EnumAvatarForceGender__NewEnumerator0 = 0,
	EnumAvatarForceGender__NewEnumerator1 = 1,
	EnumAvatarForceGender__NewEnumerator2 = 2,
	EnumAvatarForceGender__EnumAvatarForceGender_MAX = 3
};



}

