// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分08秒
namespace SDK
{
//
//Enums
//

// Enum PixUIProfiler.EPxProfilerCapability
enum class EPxProfilerCapability : uint8_t
{
	EPxProfilerCapability__PrintSizeChange = 0,
	EPxProfilerCapability__PrintCountChange = 1,
	EPxProfilerCapability__AsyncInnerData = 2,
	EPxProfilerCapability__Count   = 3,
	EPxProfilerCapability__EPxProfilerCapability_MAX = 4
};



}

