// SDK Generated by @JinxEngine .... Bypass available

#pragma once

#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function BattleItemHandle_VirtualCharacter.BattleItemHandle_VirtualCharacter_C.ExtractItemData
struct UBattleItemHandle_VirtualCharacter_C_ExtractItemData_Params
{
	struct FBattleItemData                             ReturnValue;                                              // (Parm, OutParm, ReturnParm)
};

}

