// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分21秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function Common_UIPopupBG.Common_UIPopupBG_C.Construct
struct UCommon_UIPopupBG_C_Construct_Params
{
};

// Function Common_UIPopupBG.Common_UIPopupBG_C.ExecuteUbergraph_Common_UIPopupBG
struct UCommon_UIPopupBG_C_ExecuteUbergraph_Common_UIPopupBG_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

