// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分13秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function VersionUpdate_UIBP.VersionUpdate_UIBP_C.Construct
struct UVersionUpdate_UIBP_C_Construct_Params
{
};

// Function VersionUpdate_UIBP.VersionUpdate_UIBP_C.ExecuteUbergraph_VersionUpdate_UIBP
struct UVersionUpdate_UIBP_C_ExecuteUbergraph_VersionUpdate_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

