// SDK Generated by @JinxEngine .... Bypass available

#pragma once

// 生成时间 2026年01月06日 16时15分03秒
#include "../SDK.hpp"

namespace SDK
{
//
//Parameters
//

// Function GeneralNode.GNSharedDelegate.EventTrigger
struct UGNSharedDelegate_EventTrigger_Params
{
};

}

